# Exclude a variety of commonly ignored directories and comments.
exclude = [
    "migrations",
    "nox.py",

    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = [
    "A", "C40", "C90", "E", "EM", "F", "FBT", "G", "I", "ICN", "INP", "ISC", "T10", "T20", "PGH", "PIE", "PL", "PYI",
    "RSE", "RUF", "S", "SIM", "TID", "UP", "W", "YTT"
]

# RUF100 - Remove unused `noqa` directive
ignore = ["RUF100", "A003"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["C40", "I"]
unfixable = []

per-file-ignores = {}

# Same as Black.
line-length = 120

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10.
target-version = "py311"